config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root "homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'search' => 'users#search'
    # get "daily_posts" => "users#daily_posts"
  end

  resources :groups, only: [:new, :create, :index, :show, :edit, :update] do
    get 'join' => 'groups#join'
    get 'leave' => 'groups#leave'
    get 'new/mail' => 'groups#new_mail'
    get 'send/mail' => 'groups#send_mail'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/search' => 'searches#search'

  resources :chats, only: [:show, :create]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

# ユーザーは多くの部屋に所属できる。
# ・チャットルームは多くのユーザー（今回はＤＭなので二人ですが）が所属している。
# これは多対多ですね。
# # 先ほども申しましたが今回はUser_Roomテーブルを中間テーブルとしています。
# # UserRoomテーブルの情報を参照してデータのやり取りをしていると思います。
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :rooms, through: :user_rooms, dependent: :destroy

  has_many :view_counts, dependent: :destroy

  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users

  # フォローをした、されたの関係
  # UserからみてRelationshipは多対１
  # しかし、今回Relationshipの中でもUserに対し2種類記述した為
  # 2つ記述する(する側される側で分ける）
  # しかしこのままだと存在しないテーブルを参照しようとするので
  # しっかりとRelationshipを参照する為に
  # class_name: "Relationship"でRelationshipテーブルを参照します。
  # さらに、has_manyのどっちがbelongs_toのどっちと紐づくのかが分からないので
  # フォローする側、される側のどちらのカラムを参照するかをforeign_key(外部キー)で指定(入口から入る鍵）
  # する側
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # される側
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # ここまででアソシエーションはできた

  # 一覧画面で(User.followers)などと使うときに、
  # throughでスルーするテーブル、sourceで参照するカラムを指定。
  # する側がrelationships(中間テーブル)を通して、される側すべてをとってくる（source)（出口）
  has_many :followings, through: :relationships, source: :followed
  # される側がreverse_of_relationships(中間テーブル)を通して、する側すべてをとってくる（source)
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 上の例では、reverse_of_relationshipsを越えて、relationshipからfollower_idのデータを参照します。
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50 }


  # コントローラを簡単に記述する為、ここでメソッドを用意し、後で呼び出せるようにする
  # 注意すべき点は、フォローが自分自身ではないか？とすでにフォローしていないか？の２点です
  # フォローしたときの処理
  # フォローするとき
  # followed_idと
  # follower_idが必要

  # まずは
  # ユーザーをフォローする
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているか判定
  def following?(user)
    followings.include?(user)
    # include?(含めますか？=>userを）
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def self.search_for(content, method)
    # perfectは、あとでビューの方でハッシュを使い
    # 完全一致というキーで取り出す
    if method == 'perfect'
    # ここでは取り出した物がmethodと同じならtrueで以下の処理をする
      User.where(name: content)
    elsif method == 'forwerd'
      User.where('name LIKE ?', content+'%')
    elsif method == 'backwerd'
      User.where('name LIKE ?', '%'+content)
    else
      User.where('name LIKE ?', '%'+content+'%')
    end
  end

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"#①
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"])
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  # def edit
  #   @user = User.find(params[:id])
  # end

  # ネストしているため、idが必要ない
  def edit
  end

  # def update
  #   @user = User.find(params[:id])
  #   if @user.update(user_params)
  #     redirect_to user_path(@user), notice: "You have updated user successfully."
  #   else
  #     @books = @user.books
  #     render "edit"
  #   end
  # end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user), notice: 'ゲストユーザーはプロフィール画面へ遷移できません。'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <!--フォローボタン部分テンプレートにしてなかった-->
        <td><%= render 'relationships/btn', user: user %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<div class='row'>
  <% if current_user != user %>
    <td><%= render "relationships/btn", user: user %></td>
  <% else %>
    <% if user.name != "guestuser" %>
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    <% end %>
  <% end %>

    <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
      <%= link_to 'chatを始める', chat_path(user.id), class: "ml-3" %>
    <% end %>
</div>

app/views/users/_read_data.html.erb
<div class="my-3">
  <%= form_with url: user_search_path(user), method: :get, class: "row justify-content-center", local: false do |f| %>
    <div class="col-auto">
      <%= f.date_field :created_at, class: "form-control" %>
    </div>
    <div class="col-auto">
      <%= f.submit "検索" , class: "btn btn-primary"%>
    </div>
  <% end %>
</div>
<div id="search_result">
  <% if @search_book.present? %>
    <%= render 'search', search_book: @search_book %>
  <% end %>
</div>
<h2>投稿数の前日比・前週比</h2>
<div class="table_width">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>今日の投稿数</th>
        <th>前日の投稿数</th>
        <th>前日比</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= today_book.count %></td>
        <td><%= yesterday_book.count %></td>
        <td>
          <% if today_book == 0 %>
            今日の投稿はありません
          <% elsif yesterday_book.count != 0 %>
            <% the_day_before = today_book.count / yesterday_book.count.to_f %>
            <%= (the_day_before * 100).round %>%
          <% else %>
            前日は読んでいません
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>今週の投稿数</th>
        <th>前週の投稿数</th>
        <th>前週比</th>
      </tr>
      <tr>
        <td><%= this_week_book.count %></td>
        <td><%= last_week_book.count %></td>
        <td>
          <% if this_week_book == 0 %>
            今週の投稿はありません
          <% elsif last_week_book.count != 0 %>
            <% the_week_before = this_week_book.count / last_week_book.count.to_f %>
            <%= (the_week_before*100).round %>%
          <% else %>
            前週は読んでいません
          <% end %>
        </td>
      </tr>
    </thead>
  </table>
  <b>7日間分の投稿数</b>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>6日前</th>
        <th>5日前</th>
        <th>4日前</th>
        <th>3日前</th>
        <th>2日前</th>
        <th>1日前</th>
        <th>今日</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= books.created_6days.count %></td>
        <td><%= books.created_5days.count %></td>
        <td><%= books.created_4days.count %></td>
        <td><%= books.created_3days.count %></td>
        <td><%= books.created_2days.count %></td>
        <td><%= books.created_yesterday.count %></td>
        <td><%= books.created_today.count %></td>
      </tr>
    </tbody>
  </table>
  <table>
    <tr>
      <!--そもそもこれ以下は基本の型があり、公式が用意したものを自分好みに編集する-->
      <canvas id="myLineChart"></canvas>
      <!--上でidを記述した物をしたのgetElementByIdのとこで引数としているのでおそらくそれ以下の記述と紐づいてる？-->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>
      <!--☝でこれで読み込む場合は決まったものになる？-->
      <script>
          $(document).on('turbolinks:load', function() {
            // ☝でturbokinksを無効化
          var ctx = document.getElementById("myLineChart");
          // Document の getElementById() メソッドは、 id プロパティが指定された文字列(canvas)に一致する要素を表す Element オブジェクトを返します。要素の ID は指定されていれば固有であることが求められているため、特定の要素にすばやくアクセスするには便利な方法です。
          var myLineChart = new Chart(ctx, {
            type: 'line',
            // ☝はtypeにはグラフのタイプ
            data: {
            // dataにはグラフのデータ
              labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
               //データ項目のラベル
              datasets: [
                 //データセット
                {
                  label: '投稿した本の数',
                    //凡例
                  data: [<%= books.created_6days.count %>, <%= books.created_5days.count %>, <%= books.created_4days.count %>, <%= books.created_3days.count %>, <%= books.created_2days.count %>, <%= yesterday_book.count %>, <%= today_book.count%>],
                   //グラフのデータ
                  borderColor: "rgba(0,0,255,1)",
                   //枠線の色
                  backgroundColor: "rgba(0,0,0,0)",
                  //背景色
                  tension: 0.4
                  // 張の強さ(曲線に影響）
                }
              ],
            },
            options: {
              // optionsには各種オプションを設定します。
              title: {
                display: true,
                text: '7日間の投稿数の比較'
              },
              responsive: true,
              // 多分レスポンシブ対応
              scales: {
                //軸の設定
                yAxes: [{
                  //縦軸の設定
                  ticks: {
                    //目盛りの設定
                    suggestedMax: 10,
                    // 縦軸の最大値
                    suggestedMin: 0,
                    // 縦軸の最小値？
                    stepSize: 1,
                    //数字の感覚(例えば5.10.15）のような
                    callback: function(value, index, values){
                      return  value
                    }
                  }
                }]
              },
            }
          });
        });
      </script>
    </tr>
  </table>
</div>

app/views/users/_search.html.erb
  <h2>検索結果</h2>
  <div class="card" >
    <div class="card-header">投稿数</div>
    <div class="card-body">
      <%= search_book.count %>
    </div>
  </div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= link_to "グループを作成する", new_group_path %> | <%= link_to "グループ一覧", groups_path %>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'search', search_book: @search_book) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
<!--      <table class='table table-hover table-inverse'>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th></th>-->
<!--      <th>Title</th>-->
<!--      <th>Opinion</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->
<!--  <tbody>-->
<!--    % @books.each do |book| %>-->
<!--      <tr>-->
<!--        <td>%= link_to(book.user) do %>-->
<!--          %= image_tag book.user.get_profile_image, size:'50x50' %>-->
<!--          % end %>-->
<!--        </td>-->
<!--        <td>%= link_to book.title,book %></td>-->
<!--        <td>%= book.body %></td>-->
<!--      </tr>-->
<!--    % end %>-->
<!--  </tbody>-->
<!--</table>-->
      <%= render 'books/index',books: @books %>
      <%= render 'read_data', books: @books, user: @user, today_book: @today_book, yesterday_book: @yesterday_book,this_week_book: @this_week_book, last_week_book: @last_week_book %>
    </div>
  </div>
</div>